namespace LPR381_Project.Models
{
    /// <summary>
    /// Represents a branching constraint generated by Branch & Bound.
    ///
    /// Examples:
    ///
    /// x5 <= 0
    /// x5 >= 1
    /// x3 <= 2
    /// x3 >= 3
    /// </summary>
    public class BranchConstraint
    {
        /// <summary>
        /// Zero-based index of the original decision variable.
        /// </summary>
        public int VariableIndex { get; set; }

        /// <summary>
        /// Name of the original decision variable.
        /// </summary>
        public string VariableName { get; set; }

        /// <summary>
        /// Branching operator.
        /// Normally <= or >=.
        /// </summary>
        public string Operator { get; set; }

        /// <summary>
        /// Right-hand-side value.
        /// </summary>
        public double RightHandSide { get; set; }

        public BranchConstraint()
        {
            VariableIndex = -1;
            VariableName = string.Empty;
            Operator = string.Empty;
            RightHandSide = 0.0;
        }

        /// <summary>
        /// Creates a copy of this branch constraint.
        /// </summary>
        public BranchConstraint Clone()
        {
            return new BranchConstraint
            {
                VariableIndex =
                    VariableIndex,

                VariableName =
                    VariableName,

                Operator =
                    Operator,

                RightHandSide =
                    RightHandSide
            };
        }

        public override string ToString()
        {
            return
                $"{VariableName} " +
                $"{Operator} " +
                $"{RightHandSide:F3}";
        }
    }
}